export const GalleryData = [
    {
        id:1,
        titile:"ANIMALS",
        image:"./animals/Turtle.jpg"
    },
    {
        id:2,
        titile:"ANIMALS",
        image:"./animals/20.jpg"
    },
    {
        id:3,
        titile:"ANIMALS",
        image:"./animals/BEAR.jpg"
    },
    {
        id:4,
        titile:"ANIMALS",
        image:"./animals/CAT.jpg"
    },
    {
        id:5,
        titile:"ANIMALS",
        image:"./animals/COW.jpg"
    },
    {
        id:6,
        titile:"ANIMALS",
        image:"./animals/CHEETAH.jpg"
    },
    {
        id:7,
        titile:"ANIMALS",
        image:"./animals/DEER.jpg"
    },
    {
        id:8,
        titile:"ANIMALS",
        image:"./animals/DOG.jpg"
    },
    {
        id:9,
        titile:"ANIMALS",
        image:"./animals/DUCK.jpg"
    },
    {
        id:10,
        titile:"ANIMALS",
        image:"./animals/ELEPHANT.jpg"
    },
    {
        id:11,
        titile:"ANIMALS",
        image:"./animals/FOX.jpg"
    }, {
        id:12,
        titile:"ANIMALS",
        image:"./animals/FROG.jpg"
    },
    {
        id:13,
        titile:"ANIMALS",
        image:"./animals/HAMSTER.jpg"
    },
    {
        id:14,
        titile:"ANIMALS",
        image:"./animals/LION.jpg"
    },
    {
        id:15,
        titile:"ANIMALS",
        image:"./animals/MONKEY.jpg"
    },
    {
        id:16,
        titile:"ANIMALS",
        image:"./animals/MOUSE.jpg"
    },
    {
        id:17,
        titile:"ANIMALS",
        image:"./animals/PANDA.jpg"
    },
    {
        id:18,
        titile:"ANIMALS",
        image:"./animals/PARROT.jpg"
    },
    {
        id:19,
        titile:"ANIMALS",
        image:"./animals/PENGUIN.jpg"
    },
    {
        id:20,
        titile:"ANIMALS",
        image:"./animals/RABBIT.jpg"
    },
    {
        id:21,
        titile:"CARS",
        image:"./cars/1.jpg"
    },
    {
        id:22,
        titile:"CARS",
        image:"./cars/2.jpg"
    },
    {
        id:23,
        titile:"CARS",
        image:"./cars/3.jpg"
    },
    {
        id:24,
        titile:"CARS",
        image:"./cars/4.jpg"
    },
    {
        id:25,
        titile:"CARS",
        image:"./cars/5.jpg"
    },
    {
        id:26,
        titile:"CARS",
        image:"./cars/6.jpg"
    },
    {
        id:27,
        titile:"CARS",
        image:"./cars/7.jpg"
    },
    {
        id:28,
        titile:"CARS",
        image:"./cars/8.jpg"
    },
    {
        id:29,
        titile:"CARS",
        image:"./cars/9.jpg"
    },
    {
        id:30,
        titile:"CARS",
        image:"./cars/10.jpg"
    },
    {
        id:31,
        titile:"CARS",
        image:"./cars/11.jpg"
    },
    {
        id:32,
        titile:"CARS",
        image:"./cars/12.jpg"
    },
    {
        id:33,
        titile:"CARS",
        image:"./cars/13.jpg"
    },
    {
        id:34,
        titile:"CARS",
        image:"./cars/14.jpg"
    },
    {
        id:35,
        titile:"CARS",
        image:"./cars/15.jpg"
    },
    {
        id:36,
        titile:"CARS",
        image:"./cars/16.jpg"
    },
    {
        id:37,
        titile:"CARS",
        image:"./cars/17.jpg"
    },
    {
        id:38,
        titile:"CARS",
        image:"./cars/18.jpg"
    },
    {
        id:39,
        titile:"CARS",
        image:"./cars/19.jpg"
    },
    {
        id:40,
        titile:"CARS",
        image:"./cars/201.jpg"
    },
    {
        id:41,
        titile:"motorcycles",
        image:"./motor/21.jpg"
    },
    {
        id:42,
        titile:"motorcycles",
        image:"./motor/22.jpg"
    },
    {
        id:43,
        titile:"motorcycles",
        image:"./motor/23.jpg"
    },
    {
        id:44,
        titile:"motorcycles",
        image:"./motor/24.jpg"
    },
    {
        id:45,
        titile:"motorcycles",
        image:"./motor/25.jpg"
    },
    {
        id:46,
        titile:"motorcycles",
        image:"./motor/26.jpg"
    },
    {
        id:47,
        titile:"motorcycles",
        image:"./motor/27.jpg"
    },
    {
        id:48,
        titile:"motorcycles",
        image:"./motor/28.jpg"
    },
    {
        id:49,
        titile:"motorcycles",
        image:"./motor/29.jpg"
    },
    {
        id:50,
        titile:"motorcycles",
        image:"./motor/30.jpg"
    },
    {
        id:51,
        titile:"motorcycles",
        image:"./motor/31.jpg"
    },
    {
        id:52,
        titile:"motorcycles",
        image:"./motor/32.jpg"
    },
    {
        id:53,
        titile:"motorcycles",
        image:"./motor/33.jpg"
    },
    {
        id:54,
        titile:"motorcycles",
        image:"./motor/34.jpg"
    },
    {
        id:55,
        titile:"motorcycles",
        image:"./motor/35.jpg"
    },
    {
        id:56,
        titile:"motorcycles",
        image:"./motor/36.jpg"
    },
    {
        id:57,
        titile:"motorcycles",
        image:"./motor/37.jpg"
    },
    {
        id:58,
        titile:"motorcycles",
        image:"./motor/38.jpg"
    },
    {
        id:59,
        titile:"motorcycles",
        image:"./motor/39.jpg"
    },
    {
        id:60,
        titile:"motorcycles",
        image:"./motor/40.jpg"
    },
    {
        id:61,
        titile:"tattoos",
        image:"./tattoo/41.jpg"
    },
    {
        id:62,
        titile:"tattoos",
        image:"./tattoo/42.jpg"
    },
    {
        id:63,
        titile:"tattoos",
        image:"./tattoo/43.jpg"
    },
    {
        id:64,
        titile:"tattoos",
        image:"./tattoo/44.jpg"
    },
    {
        id:65,
        titile:"tattoos",
        image:"./tattoo/45.jpg"
    },
    {
        id:66,
        titile:"tattoos",
        image:"./tattoo/46.jpg"
    },
    {
        id:67,
        titile:"tattoos",
        image:"./tattoo/47.jpg"
    },
    {
        id:68,
        titile:"tattoos",
        image:"./tattoo/48.jpg"
    },
    {
        id:69,
        titile:"tattoos",
        image:"./tattoo/49.jpg"
    },
    {
        id:70,
        titile:"tattoos",
        image:"./tattoo/50.jpg"
    },
    {
        id:71,
        titile:"tattoos",
        image:"./tattoo/51.jpg"
    },
    {
        id:72,
        titile:"tattoos",
        image:"./tattoo/52.jpg"
    },
    {
        id:73,
        titile:"tattoos",
        image:"./tattoo/53.jpg"
    },
    {
        id:74,
        titile:"tattoos",
        image:"./tattoo/54.jpg"
    },
    {
        id:75,
        titile:"tattoos",
        image:"./tattoo/55.jpg"
    },
    {
        id:76,
        titile:"tattoos",
        image:"./tattoo/56.jpg"
    },
    {
        id:77,
        titile:"tattoos",
        image:"./tattoo/57.jpg"
    },
    {
        id:78,
        titile:"tattoos",
        image:"./tattoo/58.jpg"
    },
    {
        id:79,
        titile:"tattoos",
        image:"./tattoo/59.jpg"
    },
    {
        id:80,
        titile:"tattoos",
        image:"./tattoo/60.jpg"
    },
    {
        id:81,
        titile:"sports",
        image:"./sport/61.jpg"
    },
    {
        id:82,
        titile:"sports",
        image:"./sport/62.jpg"
    },
    {
        id:83,
        titile:"sports",
        image:"./sport/63.jpg"
    },
    {
        id:84,
        titile:"sports",
        image:"./sport/64.jpg"
    },
    {
        id:85,
        titile:"sports",
        image:"./sport/65.jpg"
    },
    {
        id:86,
        titile:"sports",
        image:"./sport/66.jpg"
    },
    {
        id:87,
        titile:"sports",
        image:"./sport/67.jpg"
    },
    {
        id:88,
        titile:"sports",
        image:"./sport/68.jpg"
    },
    {
        id:89,
        titile:"sports",
        image:"./sport/69.jpg"
    },
    {
        id:90,
        titile:"sports",
        image:"./sport/70.jpg"
    },
    {
        id:91,
        titile:"sports",
        image:"./sport/71.jpg"
    },
    {
        id:92,
        titile:"sports",
        image:"./sport/72.jpg"
    },
    {
        id:93,
        titile:"sports",
        image:"./sport/73.jpg"
    },
    {
        id:94,
        titile:"sports",
        image:"./sport/74.jpg"
    },
    {
        id:95,
        titile:"sports",
        image:"./sport/75.jpg"
    },
    {
        id:96,
        titile:"sports",
        image:"./sport/76.jpg"
    },
    {
        id:97,
        titile:"sports",
        image:"./sport/77.jpg"
    },
    {
        id:98,
        titile:"sports",
        image:"./sport/78.jpg"
    },
    {
        id:99,
        titile:"sports",
        image:"./sport/79.jpg"
    },
    {
        id:100,
        titile:"sports",
        image:"./sport/80.jpg"
    },
]